version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      # - MYSQL_HOST=db
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=secret
      # - MYSQL_DATABASE=your_database

      - MYSQL_HOST=wm63be5w8m7gs25a.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
      - MYSQL_USER=lylxpkd89i9fa75b
      - MYSQL_PASSWORD=v6yphu5lfxddtqf2
      - MYSQL_DATABASE=dgy0oetsdffpvqr6

  db:
    image: mysql:8.0
    container_name: mysql
    environment:

      # MYSQL_ROOT_PASSWORD: secret
      # MYSQL_DATABASE: your_database

      MYSQL_ROOT_PASSWORD: v6yphu5lfxddtqf2
      MYSQL_DATABASE: dgy0oetsdffpvqr6
    ports:
      # - "32764:32764"
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: