version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      # - MYSQL_HOST=db
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=secret
      # - MYSQL_DATABASE=your_database

      - MYSQL_HOST=102.134.147.233
      - MYSQL_USER=vnvpyauobgavclxa
      - MYSQL_PASSWORD=secret1234
      - MYSQL_DATABASE=gsrlqftebzstmsgwkksduajx

  db:
    image: mysql:8.0
    container_name: mysql
    environment:

      # MYSQL_ROOT_PASSWORD: secret
      # MYSQL_DATABASE: your_database

      MYSQL_ROOT_PASSWORD: secret1234
      MYSQL_DATABASE: gsrlqftebzstmsgwkksduajx
    ports:
      - "32764:32764"
      # - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: